cap : imagingsource.o
	gcc imagingsource.o -lunicap

imagingsource.o : imagingsource.c
	gcc -I/usr/include/unicap -c imagingsource.c

tut_2_3 : tut_2_3.o
	gcc tut_2_3.o -lunicap

tut_2_3.o : tut_2_3.c
	gcc -I/usr/include/unicap -c tut_2_3.c

tut_2_2 : tut_2_2.o
	gcc tut_2_2.o -lunicap

tut_2_2.o : tut_2_2.c
	gcc -I/usr/include/unicap -c tut_2_2.c

tut_2_1 : tut_2_1.o
	gcc tut_2_1.o -lunicap

tut_2_1.o : tut_2_1.c
	gcc -I/usr/include/unicap -c tut_2_1.c
